### ISSUE TITLE
readme headline fix

### ISSUE THREAD

**Issue by DoctorCr4nk** [benjamingr/Auto-Translate#4]
the headlines in the readme.md are not working, i assume bc of missing whitespaces

**Comment by benjamingr** [comment]
@DoctorCr4nk I did not touch this code base in around 6 years, I have no idea if it works or how/if it's usable :]

**Comment by benjamingr** [comment]
The README headlines are problematic because of a GH change. GitHub used to make `##foo` a header but now it only makes `## foo` a header

**Comment by DoctorCr4nk** [comment]
I forked the git and fixed it, also created a merge request.
I´m suprised you answered that fast :D

**Comment by benjamingr** [comment]
I'm pretty active on GitHub overall :]

**Comment by DoctorCr4nk** [comment]
fixed
